### ISSUE TITLE
微信绑定的用户信息修改功能

### ISSUE THREAD

**Issue by yhlchao** [youthol/youthAPI#5]
用户绑定过一次信息之后，如果想修改，是需要重新提交一次完整的信息表单吗？后端是如何操作的

**Comment by oxyzhg** [comment]
@huhuapin 让聘哥过来讲一下

**Comment by huhuapin** [comment]
对，重新提交表单。前端传来code的时候，后端就已经创建了一个用户，只不过用户信息为空，只保存了openid。绑定信息就是修改信息。
