### ISSUE TITLE
微信绑定返回用户信息的学院和宿舍之间存在错误耦合

### ISSUE THREAD

**Issue by yhlchao** [youthol/youthAPI#6]
当我修改所在学院时，宿舍楼号的id同时也会被修改为学院的id；
但是单独修改宿舍楼号并不会生效。
前端的数据提交正确。

我查数据库发现，信息已经被正确修改，但是返回给前端的数据中，宿舍楼号的id受学院id控制。

我又用舍友信息进行第一次绑定，数据库信息正确存在，但是用access_token再一次请求信息，返回来的数据中宿舍楼id与学院id一致。

**Comment by huhuapin** [comment]
微信用户和宿舍模型关联bug，已修复。

**Comment by yhlchao** [comment]
好的👌
